title: Cipta Graha Software
description : Jasa Pembuatan Software Pekalongan
permalink : /:year/:month/:title/
url : https://www.ciptagrahasoftware.com
cdn : https://cdn.ciptagrahasoftware.com
show_excerpts: false # set to true to show excerpts on the homepage
paginate_path: "/blog/:num/"
paginate: 9
admin : Cgs Admin
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %b, %Y"

  # generate social links in footer
  social_links:
    #twitter: 

    whatsapp: 
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: cgsweb
#ig: https://www.instagram.com/torika_shop/
#wahalo: https://api.whatsapp.com/send/?phone=6281286860257&text=Halo%20Torika%20Shop&app_absent=0
#wabuy: https://api.whatsapp.com/send/?phone=6281286860257&text=Halo%20Apakah%20Produk
#fb: https://www.facebook.com/torikashop/
#shopee: https://shopee.co.id/torika_shop
#copyright : Copyright Â© 2021 Torika Shop
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

